embedding:
  azure_endpoint: "ENDPOINT"
  azure_deployment: "DEPLOYMENT"
  azure_api_version: "2023-05-15"
  azure_api_key: "KEY"

chat:
  azure_endpoint: "ENDPOINT"
  azure_deployment: "DEPLOYMENT"
  azure_api_version: "2023-05-15"
  azure_api_key: "KEY"
